If it's replication mode, I don't execute monitor_sql

diff --git a/heartbeat/pgsql b/heartbeat/pgsql
--- a/heartbeat/pgsql
+++ b/heartbeat/pgsql
@@ -876,23 +876,23 @@ pgsql_real_monitor() {
        fi
     fi
 
-    OCF_RESKEY_monitor_sql=`escape_string "$OCF_RESKEY_monitor_sql"`
-    runasowner -q $loglevel "$OCF_RESKEY_psql $psql_options -c '$OCF_RESKEY_monitor_sql'"
+    if ! is_replication; then
+        OCF_RESKEY_monitor_sql=`escape_string "$OCF_RESKEY_monitor_sql"`
+        runasowner -q $loglevel "$OCF_RESKEY_psql $psql_options -c '$OCF_RESKEY_monitor_sql'"
 
-    rc=$?
-    if [ $rc -ne  0 ]; then
-	ocf_log $loglevel "PostgreSQL $OCF_RESKEY_pgdb isn't running"
-        if [ $rc -eq 1 ]; then
-            ocf_log err "Fatal error (out of memory, file not found, etc.) occurred while executing the psql command."
-        elif [ $rc -eq 2 ]; then
-            ocf_log $loglevel "Connection error (connection to the server went bad and the session was not interactive) occurred while executing the psql command."
-        elif [ $rc -eq 3 ]; then
-            ocf_log err "Script error (the variable ON_ERROR_STOP was set) occurred while executing the psql command."
+        rc=$?
+        if [ $rc -ne  0 ]; then
+        ocf_log $loglevel "PostgreSQL $OCF_RESKEY_pgdb isn't running"
+            if [ $rc -eq 1 ]; then
+                ocf_log err "Fatal error (out of memory, file not found, etc.) occurred while executing the psql command."
+            elif [ $rc -eq 2 ]; then
+                ocf_log $loglevel "Connection error (connection to the server went bad and the session was not interactive) occurred while executing the psql command."
+            elif [ $rc -eq 3 ]; then
+                ocf_log err "Script error (the variable ON_ERROR_STOP was set) occurred while executing the psql command."
+            fi
+        return $OCF_ERR_GENERIC
         fi
-	return $OCF_ERR_GENERIC
-    fi
-
-    if is_replication; then
+    else
         output=`su $OCF_RESKEY_pgdba -c "cd $OCF_RESKEY_pgdata; $OCF_RESKEY_psql $psql_options -Atc '$CHECK_MS_SQL'" 2>&1`
         rc=$?
         case "$output" in
