High: pgsql: fail my resource if my data is newer then new master's.
- It is possible that new master's data is older then other slave's one
  in sync mode when three or more nodes are configured, so I check this.
- If two nodes are configured, I permit STREAMING|ASYNC to become master
  in async mode.

diff --git a/heartbeat/pgsql b/heartbeat/pgsql
--- a/heartbeat/pgsql
+++ b/heartbeat/pgsql
@@ -722,6 +722,7 @@ pgsql_stop() {
 
     change_pgsql_status "$HOSTNAME" "STOP"
     set_async_mode_all
+    delete_master_baseline
     return $OCF_SUCCESS
 }
 
@@ -890,6 +891,32 @@ pgsql_post_demote() {
     return $OCF_SUCCESS
 }
 
+pgsql_pre_promote() {
+    local master_baseline
+    local my_master_baseline
+    local cmp_location
+    local number_of_nodes
+
+    # If my data is newer then new master's one, I fails my resource.
+    PROMOTE_NODE=`echo $OCF_RESKEY_CRM_meta_notify_promote_uname | sed "s/ /\n/g" | head -1`
+    number_of_nodes=`echo $OCF_RESKEY_node_list | sed -e "s/  */ /g" | sed -e "s/^ \| $//g" | sed -e "s/ /\n/g" | wc -l`
+    if [ $number_of_nodes -ge 3 -a "$OCF_RESKEY_rep_mode" = "sync" -a "$PROMOTE_NODE" != "$HOSTNAME" ]; then
+        master_baseline=`$CRM_ATTR_REBOOT -N "$PROMOTE_NODE" -n "$PGSQL_MASTER_BASELINE" -G -q 2>/dev/null`
+        if [ $? -eq 0 ]; then
+            master_baseline=`echo $master_baseline | cut -d ":" -f 2`
+            my_master_baseline=`$CRM_ATTR_REBOOT -N "$HOSTNAME" -n "$PGSQL_MASTER_BASELINE" -G -q 2>/dev/null | cut -d ":" -f 2`
+            # get older location
+            cmp_location=`echo -e "$master_baseline\n$my_master_baseline" | sort | head -1`
+            if [ "$cmp_location" != "$my_master_baseline" ]; then
+                ocf_log err "My data is newer then new master's one. New master's location : $master_baseline"
+                $CRM_FAILCOUNT -r $OCF_RESOURCE_INSTANCE -U $HOSTNAME -v INFINITY
+                return $OCF_ERR_GENERIC
+            fi
+        fi
+    fi
+    return $OCF_SUCCESS
+}
+
 pgsql_notify() {
     local type="${OCF_RESKEY_CRM_meta_notify_type}"
     local op="${OCF_RESKEY_CRM_meta_notify_operation}"
@@ -897,6 +924,14 @@ pgsql_notify() {
 
     ocf_log debug "notify: ${type} for ${op}"
     case $type in
+        pre)
+            case $op in
+                promote)
+                    pgsql_pre_promote
+                    return $?
+                    ;;
+            esac
+            ;;
         post)
             case $op in
                 promote)
@@ -930,6 +965,7 @@ control_slave_status() {
     local all_data_status
     local tmp_data_status
     local node_name
+    local number_of_nodes
 
     all_data_status=`su $OCF_RESKEY_pgdba -c "cd $OCF_RESKEY_pgdata; $OCF_RESKEY_psql $psql_options -Atc \"${CHECK_REPLICATION_STATE_SQL}\""`
     rc=$?
@@ -942,6 +978,7 @@ control_slave_status() {
         all_data_status=""
     fi
 
+    number_of_nodes=`echo $OCF_RESKEY_node_list | sed -e "s/  */ /g" | sed -e "s/^ \| $//g" | sed -e "s/ /\n/g" | wc -l`
     for target in $OCF_RESKEY_node_list; do
         if [ "$target" = "$HOSTNAME" ]; then
             continue
@@ -975,8 +1012,12 @@ control_slave_status() {
                         set_sync_mode "$target"
                     fi
                 else
-                    change_data_status "$target" "$data_status"
-                    change_master_score "$target" "$CAN_NOT_PROMOTE"
+                    if [ $number_of_nodes -le 2 ]; then
+                        change_master_score "$target" "$CAN_PROMOTE"
+                    else
+                        # I can't determine which slave's data is newest in async mode.
+                        change_master_score "$target" "$CAN_NOT_PROMOTE"
+                    fi
                 fi
                 change_pgsql_status "$target" "HS:async"
                 ;;
